### PR TITLE
Installation instructions for Fedora packages.

### PR DESCRIPTION
**Pull request by mavit**
I made a package for easy installation on Fedora.  This pull requests links to it from the README.

### CODE REVIEW

**Comment by trigg** [comment]
From what I see this links to gitlab under your name, does this automatically track changes made to the github or use the latest release?

**Comment by trigg** [comment]
I've used your addition but placed it alongside AUR and a disclaimer.

**Comment by mavit** [comment]
It depends on me manually bumping the version number in https://gitlab.com/mavit/discover-overlay/-/blob/main/discover-overlay.spec, and fetches that version from https://pypi.org/project/discover-overlay/.

I think it should be possible to fully automate it if you prefer?

**Comment by trigg** [comment]
No worries either way. I realise with things like this pinning to a version you've tested is probably what you want, but it's more so I have an idea of what the process is and what to expect out of it.

Thanks for the PR!

**Pull request closed without merging**
