### PR TITLE
Separate Server Selection So Settings Select Succinctly

### LINKED ISSUE #53: [Feature] Grouped Server List Text
Would it be possible to group the server list into different selections on the menu like one for server than one for the text channels within that server you have selected. I see that it kind of has them grouped anyway on the list but ive got quite a few servers and some have many text channels so scrolling through the entire list takes a long time.

### PR DESCRIPTION
**Pull request by MoralCode**
Got a little carried away with the title (sorry) but essentially this PR adds another dropdown to the text setting above "channel" so that users that are in a large number of servers don't have to scroll a ton to find the right channel.
Screenshot_20201018_191511

fixes #53

### CODE REVIEW

**Comment by midget3111** [comment]
Amazing - for the name if nothing else! 
Great job :D

**Comment by trigg** [comment]
Looks very clean and well documented. Thank you!

**Comment by MoralCode** [comment]
Thanks!

Would you be open to labelling both my pull requests with a `hacktoberfest-accepted` label (or add the hacktoberfest topic to the whole repo) so that I can count these pull requests as part of hacktoberfest?

**Comment by trigg** [comment]
No problems. Will that suffice?

**Comment by MoralCode** [comment]
Perfect, thanks so much for making this overlay!

**Pull request merged**
